### ISSUE TITLE
Will part 7 be posted?

### ISSUE THREAD

**Issue by controversial** [seanmtracey/Games-with-Pygame#1]
Part 7 is in the September issue, which is available for download now, are you planning to post the code for part 7 on September 1?

**Comment by seanmtracey** [comment]
Oh! Of course! Sorry about that, it slipped my mind. It'll be up by the end of the day :)

**Comment by controversial** [comment]
Great!

**Comment by seanmtracey** [comment]
It's live right now, and you can find it here :) https://github.com/seanmtracey/Games-with-Pygame/tree/master/Part%207

**Comment by controversial** [comment]
Great, thanks :)
