### ISSUE TITLE
Solving problems with images and float error

### ISSUE THREAD

**Issue by trionam** [seanmtracey/Games-with-Pygame#10]
Hello, I had multiple problems and I have tips for you.

pygame.error: *_Unsupported image format *_

Solve by checking you really have JPG and not UTF-8 text:
 pi@raspberrypi ~/path $ file assets/game_over.jpg
 pi@raspberrypi ~/path $ file assets/title.jpg

**Float problem** occured becouse I am using **python3 *_and if you want *_to divide numbers**, you use *_// instead of / *_

Solve by replacing / by // at 2 places:
line 33   “x” : windowWidth // 2,
line 138  player[“x”] = windowWidth // 2

I hope it helped newbies as me a lot and I got idea I could add a timer (how long I stayed alive :) )...

**Comment by nickums** [comment]
I am using Python 3 with Windows 10.  In progressing from Tk to pygame, I can't get events to work,  so I have been studying mouse.py and keyboard.pi, but all I get  from them is a black screen.  I realise they are intended for RaspberryPi but why won't they work on my platform?

**Comment by nickums** [comment]
I am using Python 3 with Windows 10.  In progressing from Tk to pygame, I can't get events to work,  so I have been studying mouse.py and keyboard.pi, but all I get  from them is a black screen.  I realise they are intended for RaspberryPi but why won't they work on my platform?

**Comment by seanmtracey** [comment]
@nickums: Pygame is cross-platform, so it should work on Windows 10 just fine, although I've never been able to test it on a Windows box (macOS/Linux is what I work with day-to-day). 

If you upload your code to a [Github Gist](https://gist.github.com/), I'll take a look at it over the next few days and get back to you :)

**Comment by nickums** [comment]
Thanks Sean. The code is an exact copy and paste of yours.   The keyboard and Mouse events do not seem to happen.

**Comment by seanmtracey** [comment]
Okie dokie, Could you tell me more about the computer you're using? Manufacturer/OS version etc.

**Comment by nickums** [comment]
I have a 2.4Ghz Toshiba on windows 10.
I,m now looking at another thread about pygame on windows events not happening, so it's not your problem. Something to do with the event queue. I'm playing with adding the line pygame.event.clear()  but no joy yet. Now I've added event.pump() ;  event.get()  and I can now get the mouse click in mouse.py

**Comment by nickums** [comment]
when I look for the mouseclick, it may not be pressed at exactly that moment and so I get erratic results. I think I need to use the pygame.event  MOUSEBUTTONUP.  Let's close this conversation and thanks for your tutorial programs and support here

**Comment by seanmtracey** [comment]
👍  Good luck :)
