### ISSUE TITLE
problem with your "drop" program in the "make games" MagPi book

### ISSUE THREAD

**Issue by buzzersdad** [seanmtracey/Games-with-Pygame#11]
I copied all of the code from your website, and tried to execute it using python 3, and I got this message:
Traceback (most recent call last):
  File "/home/pi/python_games/drop_official.py", line 185, in <module>
    movePlayer()
  File "/home/pi/python_games/drop_official.py", line 52, in movePlayer
    if surface.get_at((player["x"], player["y"] + player["height"])) == (0,0,0,255):
TypeError: integer argument expected, got float

It works on python 2.  What should I change in the code to make it work on python 3? I am new at this, trying to understand how the program works.

My email address is buzzersdad@gmail.com .

**Comment by buzzersdad** [comment]
Additional problem with the code in the book - it does not increment the Clock in the main loop!  It is correct on this website.  Perhaps the book is due for an update?

**Comment by seanmtracey** [comment]
Hello!
The code in the book was written with Python 2 in mind ( > Python 2.7 ) as it was (and I think still is) the default Python version shipping with the Raspberry Pi version of Debian. At a guess (I'll check for you later this evening), casting the floats passed to the `surface.get_at` call to integers should fix the issue, like so:

`surface.get_at(( int(player["x"]), int(player["y"]) + int(player["height"]) )) == (0,0,0,255):`

Give that a go and see if it works.

**Comment by seanmtracey** [comment]
As for the clock, we made the change shortly after the Pi 3 was released as the upgrade in computational power made the games animate much faster than before. I'm unsure as to when the book will be going for an update, but for the time being, the latest code can be found in this repo.

**Comment by buzzersdad** [comment]
Works like a charm!  Thanks!
Geoff.

**Comment by seanmtracey** [comment]
You're welcome :D
