### ISSUE TITLE
x2 clock.tick in Part 10

### ISSUE THREAD

**Issue by danielhp02** [seanmtracey/Games-with-Pygame#13]
In aliens.py (Part 10), there is `GAME_TIME.Clock().tick(30)` at the top of the 'main' loop and `clock.tick(60)` at the bottom. Could you please remove one as it's a bit confusing. Thanks!

**Comment by seanmtracey** [comment]
Gosh, you're right! Must be a leftover from my debugging. Will have rectified this evening.
