### ISSUE TITLE
TypeError Found

### ISSUE THREAD

**Issue by ghost** [seanmtracey/Games-with-Pygame#15]
In the drop game, this issue is occuring on my PC  .

File "D:\Python\pygame\Games\Drop Box\dropSmash.py", line 52, in movePlayer
    if surface.get_at((player["x"], player["y"] + player["height"])) == (0,0,0,255):
TypeError: integer argument expected, got float

**Comment by seanmtracey** [comment]
Hello! Which version of Python are you running the game with?

**Comment by ghost** [comment]
Sir it's python 3.7

**Comment by seanmtracey** [comment]
Ooh, that is interesting. Do you know what values you're passing to `surface.get_at` when the error is thrown?  

If not, no worries, you can cast the values being passed to integers with something like `surface.get_at(( int(player["x"]), int(player["y"]) + int(player["height"]))) == (0,0,0,255)` which should remedy the problem :)

**Comment by ghost** [comment]
Thank you very much sir, it worked

**Comment by seanmtracey** [comment]
Anytime! Happy coding :)
