### ISSUE TITLE
Where are parts 1-3?

### ISSUE THREAD

**Issue by DaddyTheRunner** [seanmtracey/Games-with-Pygame#2]
Where can we find the code for parts 1-3?  I tried a simple cut-n-paste from the MagPi PDF for part 3.  However, the indentation was lost in the copy from the PDF due to the way the text was encoded in the PDF file.  Once, I manually fixed the indentation, I also ran into some code typos from the PDF file.  Therefore, I would like to find an online source for the code examples from the beginning parts.

**Comment by seanmtracey** [comment]
We released parts 1 - 3 before we started posting the code on Github as the examples could fit comfortably in the magazine. The code examples are a little bigger these days, so everything gets put here before we publish, but adding the first 3 parts has been on my list for a little while, so I'll let you know when I finally get a chance to push them.

**Comment by seanmtracey** [comment]
Resolved with e657ab0. Have fun!
