### ISSUE TITLE
error image_file game_over.jpg 

### ISSUE THREAD

**Issue by cindydenkt** [seanmtracey/Games-with-Pygame#5]
It is not possible for me to download the file game_over.jpg

i get the following error. 

Afbeeldingstype van bestand ‘/home/pi/Downloads/game_over.jpg’ werd niet herkend
in English Image type of the ‘/home/pi/Downloads/game_over.jpg’ was not recognized!!

**Comment by seanmtracey** [comment]
Hey there, which part of the series is this for?

**Comment by cindydenkt** [comment]
Hello Sean,
I do not know what you mean with series 
Chapter 4  CHAPTER FOUR  YOUR FIRST GAMEGames-with-Pygame/Part 4/Code/assets/  concerns the file game_over.jpgTime period of downloads 08-01-2016  till- 15-01-2016  of Github magpi.cc/1jQj9cB
I had three files1. Just_drop.py was placed in the directory /home/pi2. title.jpg was placed in the subdirectory /home/pi/assets3. game_over.jpg was placed in the subdirectory /home/pi/assetsI did not change anything of the file codesI get the following error Traceback (most recent call last):File "/home/pi/Just_drop.py", line 9, in <module>game_over_image = pygame.image.load("assets/game_over.jpg")pygame.error: Unsupported image format

So I checked if the files were 100%  JPGThe file game_over.jpg was not recognizedDeleted the file and downloaded the file again

At last two good image files (100% jpg) .1 title.jpg2 game_over.jpg (on screen game_over.jpg?raw=true)the following error on my screenTraceback (most recent call last):File "/home/pi/Just_drop.py", line 9, in <module>game_over_image = pygame.image.load("assets/game_over.jpg")pygame.error: Couldn't open assets/game_over.jpg>>> 
Then I renamed the game_over.jpg?raw=true) to  game over_jpg
Trying again with Python 3After a press on Space. I get the following errorTraceback (most recent call last):File "/home/pi/Just_drop.py", line 184, in <module>movePlayer()File "/home/pi/Just_drop.py", line 51, in movePlayerif surface.get_at((player["x"], player["y"] + player["height"])) == (0,0,0,255):TypeError: integer argument expected, got float 
This was an error caused bij Pyhon 3   (change the / to // on line 33)
Trying again  with Python 2😊 It worked with a lot of help of the forum participants!
So my first game is working and I have learned a lot.
Cindy Hesse

P Bespaar een boom, print deze mail niet, tenzij het echt moet…
…

Date: Mon, 11 Jan 2016 08:46:11 -0800

**Comment by seanmtracey** [comment]
Hey Cindy,

That's great to hear. Sorry about the 'series' confusion. Originally, this was a magazine series which has since been turned into a book. I'm still getting mixed up over my words. Glad you got it working :)
