### ISSUE TITLE
Problems with download ogg files

### ISSUE THREAD

**Issue by cindydenkt** [seanmtracey/Games-with-Pygame#7]
I want to execute my second game "Sounds.py". Chapter 5 of the Magpi magazine.
The images and sounds should be available on github magpi.cc/1sgf4Rf
I could download all the image files (100% jpg)

It is not possible to download the ogg.files (assets/sounds/OGG)
I get the following message:
cannot retrieve contributors at this time

Or
when it is possible to download the file
They are html files 

How can I solve this issue!

**Comment by seanmtracey** [comment]
Hey Cindy, If you follow this [link](https://github.com/seanmtracey/Games-with-Pygame/archive/master.zip) you should get a download which contains all of the assets for all of the parts. Let me know if that doesn't work for you.
