### ISSUE TITLE
loading images

### ISSUE THREAD

**Issue by TheHoose** [seanmtracey/Games-with-Pygame#9]
I was going through the tutorial about making this game and I ran into a problem with the images not being able to load.  I have typed everything correctly using the pygame.image.load("assets/title.jpg")  I have even downloaded the files from GitHub and not sure what I need to do so they will load. Thank you for your time.

**Comment by seanmtracey** [comment]
Hey there, which tutorial are you trying to run? If it's the book, there'll be a chapter number, if it's the MagPi you're reading, there'll be a part number at the top of the tutorial's first page. Also, are you running your code on a RasPi? If so, which one?

**Comment by TheHoose** [comment]
Hey, thanks for the reply.  I am trying the run the game Just Drop from the magpi make games with Python magazine.  I'm using the raspberry pi 2 and writing the code in Python 2(IDLE).  Not sure the part number.  It's chapter 4 your first game.  There is a download link magpi.cc/1jQj9Cb.  That's how I downloaded the images.  I've tried to look online for help but I am pretty new to coding and not sure what to do.  Thanks again, I really appreciate it.

**Comment by seanmtracey** [comment]
That's unusual, could you run the code and post the error message here (if it gives one)?. If you copy and paste the message into the comments with 3 back ticks ( ` ) either side of the message, it should maintain it's structure when you click comment.

**Comment by TheHoose** [comment]
`Traceback (most recent call last):  File "/home/pi/Documents/Python Game Projects/just_drop.py", line 8, in <module>    title_image = pygame.image.load("assets/title.jpg")error: Couldn't open assets/title.jpg>>>`
I even copied the code you have on GitHub and it gives me the same error message.  I attached my code so you can see if i wrote it wrong. Thanks! 

```
On Friday, March 25, 2016 5:58 AM, Sean Tracey <notifications@github.com> wrote:
```

 That's unusual, could you run the code and post the error message here (if it gives one)?. If you copy and paste the message into the comments with 3 back ticks ( ` ) either side of the message, it should maintain it's structure when you click comment.—

**Comment by seanmtracey** [comment]
That should work. It might be that the permissions on the file won't let you access it with the user you're running the code with. Try running `ls -la` in the same directory as your drop.py file. To the left of the assets folder, there should be something like `drwxr-xr-x` showing (which means you can read, write and execute the file). Is that what you get?

**Comment by TheHoose** [comment]
OK, that seems to have worked.  Thank you for helping me figure that out.  One last question, if you don't mind?   Why does adding the clock slow the speed of the game down?  It's not originally on the magPi magazine tutorial.  Again I really appreciate you helping me with loading the file.   

```
On Friday, March 25, 2016 12:18 PM, Sean Tracey <notifications@github.com> wrote:
```

 That should work. It might be that the permissions on the file won't let you access it with the user you're running the code with. Try running ls -la in the same directory as your drop.py file. To the left of the assets folder, there should be something like drwxr-xr-x showing (which means you can read, write and execute the file). Is that what you get?—

**Comment by seanmtracey** [comment]
Glad you got it working :)

The clock limits to framerate of the game to 60 fps. We did this because without it, more capable hardware could run the games at a faster rate than less capable hardware using the exact same code. This means that game performance would be inconsistent across different machines. For example, if you were to run the code on a Pi Zero and the same code on a Pi 3, the Pi 3 would be much, much faster as it's a fast computer. This could lead to the games being completely impossible to beat in the future, so we decided to limit them to 60 FPS.

If you want things to move faster, you can always increase the amount that you move objects by in each frame.
